# Text embedding

This notebook performs text embedding. We will the `SentenceTransformer` models from `sentence_transformers` library. These models are already trained on the embedding task so we just need to load them and use without any training.

https://www.sbert.net/docs/pretrained_models.html

We will use the `MPNet` embedding model.

The embedded data will be saved as `numpy` data objects for the models to use.


# Load model

In [1]:
#install package if not available
!pip install sentence_transformers

Requirement already satisfied: sentence_transformers in /home/aanis/venv/lib/python3.11/site-packages (5.3.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /home/aanis/venv/lib/python3.11/site-packages (from sentence_transformers) (5.3.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /home/aanis/venv/lib/python3.11/site-packages (from sentence_transformers) (1.7.1)
Requirement already satisfied: torch>=1.11.0 in /home/aanis/venv/lib/python3.11/site-packages (from sentence_transformers) (2.10.0)
Requirement already satisfied: numpy in /home/aanis/venv/lib/python3.11/site-packages (from sentence_transformers) (2.4.3)
Requirement already satisfied: scikit-learn in /home/aanis/venv/lib/python3.11/site-packages (from sentence_transformers) (1.8.0)
Requirement already satisfied: scipy in /home/aanis/venv/lib/python3.11/site-packages (from sentence_transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /home/aanis/venv/lib/python3.11/site-packages (from sentence_transformers) (4.15.0)
Requirement already satisfied: tqdm in /home/aanis/venv/lib/python3.11/site-packages (from sentence_transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /home/aanis/venv/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /home/aanis/venv/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /home/aanis/venv/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/aanis/venv/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /home/aanis/venv/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /home/aanis/venv/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (6.0.3)
Requirement already satisfied: typer in /home/aanis/venv/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (0.24.1)
Requirement already satisfied: sympy>=1.13.3 in /home/aanis/venv/lib/python3.11/site-packages (from torch>=1.11.0->sentence_transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/aanis/venv/lib/python3.11/site-packages (from torch>=1.11.0->sentence_transformers) (3.6.1)
Requirement already satisfied: jinja2 in /home/aanis/venv/lib/python3.11/site-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /home/aanis/venv/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/aanis/venv/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /home/aanis/venv/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.7.0)
Requirement already satisfied: joblib>=1.3.0 in /home/aanis/venv/lib/python3.11/site-packages (from scikit-learn->sentence_transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /home/aanis/venv/lib/python3.11/site-packages (from scikit-learn->sentence_transformers) (3.6.0)
Requirement already satisfied: anyio in /home/aanis/venv/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (4.12.1)
Requirement already satisfied: certifi in /home/aanis/venv/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /home/aanis/venv/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (1.0.9)
Requirement already satisfied: idna in /home/aanis/venv/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /home/aanis/venv/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/aanis/venv/lib/python3.11/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/aanis/venv/lib/python3.11/site-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /home/aanis/venv/lib/python3.11/site-packages (from typer->huggingface-hub>=0.20.0->sentence_transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /home/aanis/venv/lib/python3.11/site-packages (from typer->huggingface-hub>=0.20.0->sentence_transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /home/aanis/venv/lib/python3.11/site-packages (from typer->huggingface-hub>=0.20.0->sentence_transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/aanis/venv/lib/python3.11/site-packages (from typer->huggingface-hub>=0.20.0->sentence_transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/aanis/venv/lib/python3.11/site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence_transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/aanis/venv/lib/python3.11/site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence_transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /home/aanis/venv/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence_transformers) (0.1.2)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [3]:
pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

Collecting google-api-python-client
  Downloading google_api_python_client-2.192.0-py3-none-any.whl.metadata (7.0 kB)
Collecting google-auth-httplib2
  Downloading google_auth_httplib2-0.3.0-py3-none-any.whl.metadata (3.1 kB)
Collecting google-auth-oauthlib
  Downloading google_auth_oauthlib-1.3.0-py3-none-any.whl.metadata (2.9 kB)
Collecting httplib2<1.0.0,>=0.19.0 (from google-api-python-client)
  Downloading httplib2-0.31.2-py3-none-any.whl.metadata (2.2 kB)
Collecting google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 (from google-api-python-client)
  Downloading google_auth-2.49.1-py3-none-any.whl.metadata (6.2 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 (from google-api-python-client)
  Downloading google_api_core-2.30.0-py3-none-any.whl.metadata (3.1 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client)
  Downloading uritemplate-4.2.0-py3-none-any.whl.metadata (2.6 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib)
  Using cached requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting googleapis-common-protos<2.0.0,>=1.56.3 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading googleapis_common_protos-1.73.0-py3-none-any.whl.metadata (9.4 kB)
Collecting protobuf<7.0.0,>=4.25.8 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Using cached protobuf-6.33.5-cp39-abi3-manylinux2014_aarch64.whl.metadata (593 bytes)
Collecting proto-plus<2.0.0,>=1.22.3 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading proto_plus-1.27.1-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /home/aanis/venv/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.32.5)
Collecting pyasn1-modules>=0.2.1 (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client)
  Using cached pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting cryptography>=38.0.3 (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client)
  Downloading cryptography-46.0.5-cp311-abi3-manylinux_2_34_aarch64.whl.metadata (5.7 kB)
Collecting pyparsing<4,>=3.1 (from httplib2<1.0.0,>=0.19.0->google-api-python-client)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib)
  Using cached oauthlib-3.3.1-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: cffi>=2.0.0 in /home/aanis/venv/lib/python3.11/site-packages (from cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (2.0.0)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client)
  Downloading pyasn1-0.6.3-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/aanis/venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /home/aanis/venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/aanis/venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/aanis/venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2026.2.25)
Requirement already satisfied: pycparser in /home/aanis/venv/lib/python3.11/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (3.0)
Downloading google_api_python_client-2.192.0-py3-none-any.whl (14.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 596.8 kB/s eta 0:00:0000:0100:01
Downloading google_auth_httplib2-0.3.0-py3-none-any.whl (9.5 kB)
Downloading google_auth_oauthlib-1.3.0-py3-none-any.whl (19 kB)
Downloading google_api_core-2.30.0-py3-none-any.whl (173 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.3/173.3 kB 454.3 kB/s eta 0:00:00a 0:00:01
Downloading google_auth-2.49.1-py3-none-any.whl (240 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.7/240.7 kB 366.3 kB/s eta 0:00:0000:0100:01
Downloading httplib2-0.31.2-py3-none-any.whl (91 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.1/91.1 kB 948.3 kB/s eta 0:00:000:00:01m
Using cached requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Downloading uritemplate-4.2.0-py3-none-any.whl (11 kB)
Downloading cryptography-46.0.5-cp311-abi3-manylinux_2_34_aarch64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 356.2 kB/s eta 0:00:0000:0100:01
Downloading googleapis_common_protos-1.73.0-py3-none-any.whl (297 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.6/297.6 kB 230.1 kB/s eta 0:00:0000:0100:01
Using cached oauthlib-3.3.1-py3-none-any.whl (160 kB)
Downloading proto_plus-1.27.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 kB 316.0 kB/s eta 0:00:00a 0:00:01
Using cached protobuf-6.33.5-cp39-abi3-manylinux2014_aarch64.whl (324 kB)
Using cached pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.8/122.8 kB 321.0 kB/s eta 0:00:00a 0:00:01
Downloading pyasn1-0.6.3-py3-none-any.whl (83 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 358.0 kB/s eta 0:00:00a 0:00:01
Installing collected packages: uritemplate, pyparsing, pyasn1, protobuf, oauthlib, requests-oauthlib, pyasn1-modules, proto-plus, httplib2, googleapis-common-protos, cryptography, google-auth, google-auth-oauthlib, google-auth-httplib2, google-api-core, google-api-python-client
Successfully installed cryptography-46.0.5 google-api-core-2.30.0 google-api-python-client-2.192.0 google-auth-2.49.1 google-auth-httplib2-0.3.0 google-auth-oauthlib-1.3.0 googleapis-common-protos-1.73.0 httplib2-0.31.2 oauthlib-3.3.1 proto-plus-1.27.1 protobuf-6.33.5 pyasn1-0.6.3 pyasn1-modules-0.4.2 pyparsing-3.3.2 requests-oauthlib-2.0.0 uritemplate-4.2.0

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [9]:
# from google.colab import drive
# drive.mount('/content/drive')
import pandas as pd
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

# Load data

Now we perform embedding at the full-text level - one answer results in one numeric vector. The data path can be changed to other available datasets in the `Data` folder. The data name will be used to save the full-text and sentence embedding data objects.

In [7]:
import pandas as pd

dataset = 'SQUAD_GPT4'

data = pd.read_csv(f'/home/aanis/Metric-Models-for-Detection-of-LLM-Texts/Data/{dataset}.csv')

data.head()

,id,question,answer,gpt1,gpt2
0,0,When did Beyoncé rise to fame?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,Beyoncé rose to fame in the late 1990s as the ...,Beyoncé rose to fame in the late 1990s as the ...
1,6,When did Destiny's Child release their second ...,The group changed their name to Destiny's Chil...,"Destiny's Child, the iconic R&B girl group, re...","Destiny's Child, the iconic American R&B group..."
2,11,Destiny's Child's final album was named what?,"In November 2003, she embarked on the Dangerou...",Destiny's Child's final studio album is titled...,Destiny's Child's final studio album was title...
3,12,How many copies did B'Day sell during the firs...,Beyoncé's second solo album B'Day was released...,"Beyoncé's album ""B'Day"" had a successful first...","Beyoncé's second studio album, ""B'Day,"" had a ..."
4,18,In which year was reports about Beyonce perfor...,"In 2011, documents obtained by WikiLeaks revea...",Reports about Beyoncé performing for Muammar G...,Reports about Beyoncé performing for Muammar G...

# Full-text embedding

Perform one answer to one embedding is very simple. We use `model.encode()`, for example:

The result is a 768-dimension vector. To apply the transformation on the whole data, we use the `apply()` function from `pandas`. Make sure to have the correct columns names from your data.

In [13]:
from tqdm import tqdm
tqdm.pandas()

answer_embs = data['answer'].progress_apply(lambda x: model.encode(x))

100%|██████████| 4306/4306 [24:09<00:00,  2.97it/s]

In [14]:
gpt1_embs = data['gpt1'].progress_apply(lambda text: model.encode(text))
gpt2_embs = data['gpt2'].progress_apply(lambda text: model.encode(text))

100%|██████████| 4306/4306 [21:26<00:00,  3.35it/s]
100%|██████████| 4306/4306 [20:57<00:00,  3.42it/s]

Finally, save the embedding data. Be sure to change the file names before saving.

In [16]:
import pickle

with open(f'/home/aanis/Metric-Models-for-Detection-of-LLM-Texts/Data/{dataset}_answer_embs.obj','wb') as f:
  pickle.dump(answer_embs, f)
with open(f'/home/aanis/Metric-Models-for-Detection-of-LLM-Texts/Data/{dataset}_gpt1_embs.obj','wb') as f:
  pickle.dump(gpt1_embs, f)
with open(f'/home/aanis/Metric-Models-for-Detection-of-LLM-Texts/Data/{dataset}_gpt2_embs.obj','wb') as f:
  pickle.dump(gpt2_embs, f)

# Sentence embedding

Next, we perform embedding at the sentence level. We still follow the previous process, however, with one added step. We need to split the answers into sentences first. This requires the `sent_tokenize()` function from the `nltk` library.

New columns will be stored directly in the original dataframe. Each answer will be transformed to a list of sentences.

In [21]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.tokenize import sent_tokenize

data.loc[:, 'answer_sentences'] = data['answer'].apply(lambda x: sent_tokenize(x))
data.loc[:, 'gpt1_sentences'] = data['gpt1'].apply(lambda x: sent_tokenize(x))
data.loc[:, 'gpt2_sentences'] = data['gpt2'].apply(lambda x: sent_tokenize(x))
data.head()

[nltk_data] Downloading package punkt to /home/aanis/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/aanis/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

,id,question,answer,gpt1,gpt2,answer_sentences,gpt1_sentences,gpt2_sentences
0,0,When did Beyoncé rise to fame?,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,Beyoncé rose to fame in the late 1990s as the ...,Beyoncé rose to fame in the late 1990s as the ...,[Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ ...,[Beyoncé rose to fame in the late 1990s as the...,[Beyoncé rose to fame in the late 1990s as the...
1,6,When did Destiny's Child release their second ...,The group changed their name to Destiny's Chil...,"Destiny's Child, the iconic R&B girl group, re...","Destiny's Child, the iconic American R&B group...",[The group changed their name to Destiny's Chi...,"[Destiny's Child, the iconic R&B girl group, r...","[Destiny's Child, the iconic American R&B grou..."
2,11,Destiny's Child's final album was named what?,"In November 2003, she embarked on the Dangerou...",Destiny's Child's final studio album is titled...,Destiny's Child's final studio album was title...,"[In November 2003, she embarked on the Dangero...",[Destiny's Child's final studio album is title...,[Destiny's Child's final studio album was titl...
3,12,How many copies did B'Day sell during the firs...,Beyoncé's second solo album B'Day was released...,"Beyoncé's album ""B'Day"" had a successful first...","Beyoncé's second studio album, ""B'Day,"" had a ...",[Beyoncé's second solo album B'Day was release...,"[Beyoncé's album ""B'Day"" had a successful firs...","[Beyoncé's second studio album, ""B'Day,"" had a..."
4,18,In which year was reports about Beyonce perfor...,"In 2011, documents obtained by WikiLeaks revea...",Reports about Beyoncé performing for Muammar G...,Reports about Beyoncé performing for Muammar G...,"[In 2011, documents obtained by WikiLeaks reve...",[Reports about Beyoncé performing for Muammar ...,[Reports about Beyoncé performing for Muammar ...

Finally, apply the `model.encode()` function again. Notice here we apply this function on the sentence columns, not the original.

In [22]:
answer_sentences_embs = data['answer_sentences'].progress_apply(lambda x: model.encode(x))
gpt1_sentences_embs = data['gpt1_sentences'].progress_apply(lambda x: model.encode(x))
gpt2_sentences_embs = data['gpt2_sentences'].progress_apply(lambda x: model.encode(x))

100%|██████████| 4306/4306 [33:01<00:00,  2.17it/s]
100%|██████████| 4306/4306 [30:24<00:00,  2.36it/s]
100%|██████████| 4306/4306 [29:45<00:00,  2.41it/s]

In [25]:
import pickle

with open('/home/aanis/Metric-Models-for-Detection-of-LLM-Texts/Data/{dataset}_answer_sentence_embs.obj','wb') as f:
  pickle.dump(answer_sentences_embs, f)
with open('/home/aanis/Metric-Models-for-Detection-of-LLM-Texts/Data/{dataset}_gpt1_sentence_embs.obj','wb') as f:
  pickle.dump(gpt1_sentences_embs, f)
with open('/home/aanis/Metric-Models-for-Detection-of-LLM-Texts/Data/{dataset}_gpt2_sentence_embs.obj','wb') as f:
  pickle.dump(gpt2_sentences_embs, f)

### Save all embeddings for future use

In [26]:
import numpy as np

#save full text embeddings
np.save("answer_embs.npy", answer_embs)
np.save("gpt1_embs.npy", gpt1_embs)
np.save("gpt2_embs.npy", gpt2_embs)

#save sentence level embeddings
np.save("answer_sentences_embs.npy", answer_sentences_embs)
np.save("gpt1_sentences_embs.npy", gpt1_sentences_embs)
np.save("gpt2_sentences_embs.npy", gpt2_sentences_embs)

In [29]:
np.savez(f'/home/aanis/Metric-Models-for-Detection-of-LLM-Texts/Data/{dataset}_embeddings.npz',
         answer=answer_embs,
         gpt1=gpt1_embs,
         gpt2=gpt2_embs)


np.savez(f'/home/aanis/Metric-Models-for-Detection-of-LLM-Texts/Data//{dataset}_embeddings.npz',
         answer_sentences=answer_sentences_embs,
         gpt1_sentences=gpt1_sentences_embs,
         gpt2_sentences=gpt2_sentences_embs)